### ISSUE TITLE
Include other collections

### ISSUE THREAD

**Issue by gabrieljaegerde** [niklasp/govrewards#1]
Please consider the other item collections as well as the shelf collection here too.

https://github.com/niklasp/govrewards/blob/2fa59d4d1364d64996e3326ffccf183821d75020/src/components/ui/nft-feed.js#L42

**Comment by gabrieljaegerde** [comment]
As for the web3Go button, I think maybe we remove it as otherwise it gets confusing if it just shows the item collection?

**Comment by tumispro** [comment]
Resolved, closing this. Not sure about the button removal. @niklasp what do you think?
