### ISSUE TITLE
Ref 217 sometimes shows the wrong art

### ISSUE THREAD

**Issue by tumispro** [niklasp/govrewards#14]
Shared art is shown instead of the main resource

**Comment by gabrieljaegerde** [comment]
i think for that one we need to add a special condition to not use the shared art thumb.

**Comment by tumispro** [comment]
Could be, but I am guessing this will be a recurring issue. We query grouped data, which results in the metadata of specific NFT's being picked up. I think that if they have a different resource set this issue occurs. Will investigate now :)

Solution might be to fetch all resources and pick the first one, which is always the correct one if I'm not mistaken.

**Comment by tumispro** [comment]
Oh my, fetching resources and picking the first in the grouped query works like a charm. This also speeds up the process a lot! We used to query every thumb standalone, similar to Singular, but we differ in usecase and always need the default image so this is way better for us :)
