### ISSUE TITLE
Fix: Modal Issues

### ISSUE THREAD

**Issue by gabrieljaegerde** [niklasp/govrewards#4]
<img width="791" alt="Screenshot 2022-08-22 at 18 46 34" src="https://user-images.githubusercontent.com/45383420/185975107-249e765c-7999-40d5-8a5c-d88d5ce96215.png">

Please make the modal scrollable in order to see all the content. I currently cannot see the vote buttons.

**Comment by gabrieljaegerde** [comment]
Both green and yellow boxes currently also not update as I select different wallets.

**Comment by gabrieljaegerde** [comment]
Text of the green box should be you have "the chance to receive a luck boost of 50%"

**Comment by niklasp** [comment]
@gabrieljaegerde feel free to submit tiny text changes directly in github, basically it is all placeholders

**Comment by niklasp** [comment]
https://github.com/niklasp/govrewards/blob/2fa59d4d1364d64996e3326ffccf183821d75020/src/components/modals/referendum-vote.js#L97 also can edit in github directly, no need for opening your dev env

**Comment by niklasp** [comment]
also that process might need to be described somewhere maybe. I would not understand it as a user, what is luck boost? for what? is it in the docs?

**Comment by gabrieljaegerde** [comment]
True. Let's throw that in the Q&A

**Comment by niklasp** [comment]
can you do that? or otherwise put it here i will put it in

**Comment by gabrieljaegerde** [comment]
I reformulated it as I think the luck boost concept actually overcomplicates things.
